### PR TITLE
Fix/large module size

### PR DESCRIPTION
**Pull request by markstuart**
I noticed that the example geojson files were ~28MB in size, which seems a little hefty for users to pull down when they `npm install`.

I'm not sure if my approach with the parser example works for you, let me know what you think. Was the intention of that file to just demonstrate how one might go about creating geojson with start-end properties? Or were you using it for development?

Anyway, just an idea that I thought might help the module size a bit.

### CODE REVIEW

**Comment by skeate** [comment]
Thanks you for the PRs and issue report!

I don't think I'll be merging this one, though.

`border-parse.js` is specifically for `borders.json` -- it's not really a "standard" format (`properties` in GeoJSON is arbitrary data). It's partly for development (at least, originally) and partly as a demo of how one might process a GeoJSON file that's not exactly in the right format.

`borders.json` was included because the generation of it requires extra software, and I'd like to avoid that need.

I agree the json data is not necessary for use in production, but rather than just deleting it here, it could be put into a `.npmignore`. It'll still be included if they pull the entire repo, but deleting it wouldn't help with that anyway (it's still in the git history and the `gh-pages` branch).

**Comment by skeate** [comment]
`.npmignore` added in 3178ed64f0819684648465eb3f041f7855dc9749

**Comment by markstuart** [comment]
Oh, yeah, that's a much better idea @skeate :+1:

I'm keen to contribute to your project if you're interested. Is there a preferred way for us to discuss ideas before I go down the path of implementing unwanted changes? Perhaps a Gitter chat room? Or just open an issue for it? My preference would be Gitter.

**Comment by skeate** [comment]
I've started a Gitter chatroom!

**Pull request closed without merging**
