### PR TITLE
Controls updates

### PR DESCRIPTION
**Pull request by theopolisme**
Thanks for the very useful plugin. Here's one bugfix and one feature for the playback/controls functionality:

- **Update output on prev/next button clicks**: Previously, clicking the prev/next buttons would move the range slider, but not update the date displayed in the output container. This is now fixed.
- **Allow playback to be controlled using the keyboard**: Allow playback to be controlled using the spacebar (play/pause) and right/left arrow keys (next/previous). Can be disabled by setting `enableKeyboardControls` to false.

Cheers,

### CODE REVIEW

**Comment by skeate** [comment]
Thanks! My only concern is the default being `true` for `enableKeyboardControls`, at least with the event bindings on the `document` itself, and not some more localized element (though I'm not sure what would be able to capture the events -- perhaps the range input?). It's fine if on a page where the map is the main focus, but otherwise it seems surprising.

**Comment by theopolisme** [comment]
Fair enough. Hm, I feel like binding to a more specific element might be of limited utility as it requires the user to focus the element before navigating with the keyboard (when in reality not everyone is going to want to first scrub through the timeline--maybe they just want to hit play)...

One option is adding a tabIndex to the `.leaflet-timeline-controls` and then accepting keyboard inputs on the entire controls container. And, as you said, the range input is an option (by default `<input type="range">` already listens to left/right arrows, so just adding the spacebar wouldn't be too much of a step :smile:). Or `enableKeyboardControls` could just be false by default (maybe the easiest way to go about things)... your opinion?

**Comment by skeate** [comment]
I think just defaulting it to `false` is fine.

**Comment by theopolisme** [comment]
Updated, thanks.

**Pull request merged**
