### PR TITLE
Custom data

### PR DESCRIPTION
**Pull request by vencax**
Hi, I'd like to use your plugin but have not data i form that the plugin awaits. So I made little mod to be able to inject methods that can handle the diffs. The changes does not affect original behavior.
Maybe you would like that ... thanks, bye

### CODE REVIEW

**Comment by skeate** [comment]
Thanks for the contribution!  Some notes: 

1. I'm not getting the purpose of passing in `addData` or `doSetTime`. Can you give an example where one might want to change their functionality?
2. Nitpick 1: `intervaFromFeature` should be `intervalFromFeature`
3. Nitpick 2: Might be better for `intervalFromFeature` to return an object with `start` and `end` properties, rather than just an array. Makes the code a bit clearer.

**Comment by vencax** [comment]
2, 3 - my mistake, I will fix it.
1 - addData is the part that expects data with hardwired structure, _addData is the rest part (independent on data structure).

**Comment by vencax** [comment]
setTime: I need not to run drawing part in setTime. I need to set time property and call change handlers. So I have split the method into 2 parts and the second made configurable. I admint, that there could be cleaner solution.

**Comment by skeate** [comment]
Well, if it works for your use case and doesn't affect the default behavior, I see no problem with it. Just trying to understand it in case I need to make changes around it later.

Thanks!

**Pull request merged**
